db_host: product-testing-instance.c2nq63ptnoe7.eu-north-1.rds.amazonaws.com
db_password: Lorem123
db_user: postgres
db_port: 5432
db_name: mocks
db_schema: public
db_tables:
  - rides
replication_slot_name: morning_elephant
tls_verify: require
stream_old_data: true